### ISSUE TITLE
unable to disable title

### ISSUE THREAD

**Issue by AasharWahla** [firatcetiner/list_tile_switch#1]
Is there any way to disable title property?

**Comment by firatcetiner** [comment]
> Is there any way to disable title property?

I can add an option for disabling it.

**Comment by AasharWahla** [comment]
yes exactly, and I will recommend that it should take only take the space for the switch.

**Comment by firatcetiner** [comment]
I'm closing this since version `1.0.0` solves it. I have opted-in this package to null-safety as well. Please use the latest version in order to take advantage of the new Flutter (2.0) and Dart (>=2.12) SDKs.
